# --- checkpoint dir ---
checkpoint_dir: checkpoint

# --- dataset ---
dataset_dir: /mnt/disks/sdb/dev_dataset  # Dataset dir must contain metadata json file
split_ratio: 0.8  # eval split ratio

# --- model_name ---
# 1. SimCLR
# 2. BYOL
# 3. Conv2d_AE
pretrain_model: BYOL

# --- SimCLR option ---
SimCLR_option:     

    size_w_rep: 512    
    train: True    
    temperature: 0.07
    project_head: 1
    
    
# --- BYOL option ---
BYOL_option:

    hidden_size: 4096        
    size_w_rep: 512    
    project_head: 1
    predict_head: 1
    

# --- Conv2d_AE option ---
Conv2d_AE_option:
    
    dilation: False
    latent_size: 512
    
# --- pretrain option ---
pretrain: False
pretrain_epoch: 10
pretrain_batch_size: 64

# --- linear evalutation option ---
# Logistic regression for genre classification.
linear: True
linear_epoch: 200
linear_batch_size: 128
num_classes: 14
linear_lr: 0.001
    
    